name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        options: --health-cmd "mysqladmin ping --silent" --health-interval 10s --health-timeout 5s --health-retries 3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up MySQL
      run: |
        sudo apt-get update
        sudo apt-get install mysql-client -y
        mysql --host=localhost --port=3306 -u root -proot -e "CREATE DATABASE bankiapp"
        mysql --host=localhost --port=3306 -u root -proot -e "CREATE USER 'testuser'@'%' IDENTIFIED BY 'testpassword'"
        mysql --host=localhost --port=3306 -u root -proot -e "GRANT ALL PRIVILEGES ON testdb.* TO 'testuser'@'%'"

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test

    - name: Build artifact
      run: mvn clean install
